In the same repository, create a file named manual.yml in the .github/workflows folder
Add the code below to the newly created file
name: manual
on:
  workflow_dispatch:
    inputs:
      name:
        description: The name to echo
        default: World
        required: false
jobs:
  manual:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello ${{ github.event.inputs.name }}"